use_frameworks!

target 'YDProject_Example' do
  pod 'YDProject', :path => '../'


  pod 'Masonry'
  pod 'ReactiveCocoa', '~>2.5'
  pod 'PaulGeorge', :git=> 'https://github.com/sakuragiten/PaulGeorge.git'

  target 'YDProject_Tests' do
    inherit! :search_paths

    
  end
end
