
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YDProject_Example' do
  pod 'YDProject', :path => '../'


  pod 'Masonry'
  pod 'ReactiveCocoa', '~>2.5'
  pod 'PaulGeorge', :git=> 'https://github.com/sakuragiten/PaulGeorge.git'
  
  pod 'ZFPlayer', '~> 3.0'
  pod 'ZFPlayer/ControlView', '~> 3.0'
  pod 'ZFPlayer/AVPlayer', '~> 3.0'
  
  pod 'SAMKeychain', '~> 1.5.3'
  pod 'SDWebImage'
  
  pod 'Texture'
  
  target 'YDProject_Tests' do
    inherit! :search_paths

    
  end
end
